### ISSUE TITLE
A Javascript error occured in the browser process

### ISSUE THREAD

**Issue by halhenke** [sindresorhus/gulp-app#24]
when I open the app:

```
Uncaught Exception:
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:467:13)
    at Object.<anonymous> (/Applications/Gulp.app/Contents/Resources/atom.asar/browser/lib/init.js:102:21)
    at Object.<anonymous> (/Applications/Gulp.app/Contents/Resources/atom.asar/browser/lib/init.js:104:4)
    at Module._compile (module.js:418:26)
    at Object.Module._extensions..js (module.js:436:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:298:12)
    at Function.Module.runMain (module.js:459:10)
    at startup (node.js:131:18)
    at node.js:879:3
```

**Comment by sindresorhus** [comment]
Use the ready built one: https://github.com/sindresorhus/gulp-app/releases

I haven't had the chance to look into why building master fails.

**Comment by halhenke** [comment]
OK thanks

**Comment by sindresorhus** [comment]
Closing as this app is now deprecated.
